app = "salesbot" # Pastikan baris ini sesuai nama unik botmu
primary_region = "sin"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080" # Default port untuk banyak web apps, harus sesuai dengan yang digunakan Python app-mu

[http_service]
  internal_port = 8080 # Harus sama dengan PORT di [env]
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.ports]]
  port = 80
  handlers = ["http"]

[[http_service.ports]]
  port = 443
  handlers = ["tls", "http"]
